# .github/workflows/stats.yml
name: Update GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Daily
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats
        run: |
          # Use a reliable stats generator
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=zafrose3&show_icons=true"